### PR TITLE
Updated README.md to reflect latest changes

### LINKED ISSUE #36: Running example command in image from README yields an error
Running the following example inside image from [Defining and invoking commands](https://github.com/pharo-contributions/clap-st#defining-and-invoking-commands) yields a `Instance of ClapCommand did not understand #runWith:` error

Screenshot from 2023-11-14 15-02-31

### PR DESCRIPTION
**Pull request by Bajger**
- updated status information about CLAP project
- fixed project references
- fixed example with command execution
- added Christophe as contributor
- fixes #36

### CODE REVIEW

**Comment by Bajger** [comment]
@cdlm @demarey Thanks for review!
I'm not sure, if comment about Fari still makes sense:
> Shameless plug: I work with [Fari](https://people.untyped.org/fari.sh) and
[direnv](https://direnv.net) to automate building and launching the development image:

> ```shell
> # setup $PHARO
> fari build
> fari run
> ```

**Review by cdlm — COMMENTED** [review]
looks good to me

**Comment by Bajger** [comment]
@cdlm I don't have write access to merge PR, so feel free to merge it!

**Comment by cdlm** [comment]
The Pharo team seems to have adopted new processes so I'll leave it to @demarey

**Comment by Bajger** [comment]
@demarey Hi Christophe! Can you approve&merge this PR? Thanks!

**Comment by hernanmd** [comment]
It would be nice to see the updated README. @demarey ?

**Pull request merged**
